FROM python:3.12-bookworm as base

COPY --from=ghcr.io/astral-sh/uv:0.7.14 /uv /bin/uv
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

WORKDIR /app
COPY uv.lock pyproject.toml /app/
ADD src/ /app/
RUN uv sync --locked

RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts && \
  ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN --mount=type=secret,id=gitconfig,target=/root/.gitconfig \
  --mount=type=ssh \
  uv sync --locked

CMD ["uv", "run", "python", "-m", "src"]
